# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create( name: "Richard", email: "runthisshit@gmail.com", password:"1234")

Spot.create( name: "Brooklyn Banks", address: "355 Pearl St, New York, NY 10038", boro: "manhattan", trains: "Chambers St J/M/Z and 4/5/6", obstacles: "Steep bank, stair sets, rails, DIY boxes, etc.", rating: 5, description: "Probably the most famous spot in NYC, featured in tons of video games and movies. Has gone through many life cycles from open skatepark to city construction storage. Open for the time being, can you really call yourself an skateboarder in NY without having done at least a trick here? Debatable.", directions: "Get off at chambers st station head to the police station, go under the bridge, might have to sneak your way in, sometimes open sometimes not", bust_factor: "You will not be bothered here.", noteworthy: "Ian Michna - No Comply", photo_main: "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fwp-content%2Fblogs.dir%2F13%2Ffiles%2F2017%2F04%2F11611_brooklyn-banks-2017_coverImage.jpg?w=960&cbr=1&q=90&fit=max", photo2: "https://format-com-cld-res.cloudinary.com/image/private/s--PL9rd0ad--/c_limit,g_center,h_1200,w_65535/fl_keep_iptc.progressive,q_95/v1/b21ff36256b5a820f0839292ad1cc8d8/Danny_Salgado_no_comply_tailslide-brooklyn_banks.jpg", photo3: "https://dslv9ilpbe7p1.cloudfront.net/EQaYtV2a2OYStr_GhNi0KA_store_header_image", phto4: "https://blogs.baruch.cuny.edu/eng2100essesfall/files/2015/12/ot1k21cpkdvbaqfltktl.jpg", user_id: 1)

Spot.create(name: "Black Marble Hubba", address: "65-55 Centre St, New York, NY 10007", boro: "manhattan", trains: "4/5/6 and J/Z at City Hall/Brooklyn Bridge", obstacles: "Slick black marble ledges down stair sets.", rating: 4, description: "If you haven't skated here you most assuredly know it from videos. Decently high and slick. You probably have some sort of flow/hook up if you are skating here but if you can skate it definitely worth it. Some of the ledges can be hit from flat, but just kissing the ledge.", bust_factor: "Its possible but probably won't be hassled.", noteworthy: "Alot has been done here", directions: "Get off the subway, skate down hill, you will see it", photo_main: "https://storage.googleapis.com/fsscs1/images/large/41a9e56ede865686c6517d76d94b97f7.jpg", photo2: "https://i.ytimg.com/vi/DHzxAS_2oo0/maxresdefault.jpg", photo3: "https://quartersnacks.com/wp-content/uploads/2010/05/blackhubba1.jpg", user_id: 1)

 Spot.create(name: "C-Benches", address: "88 Pine St, New York, NY 10005", boro: "manhattan", trains: "2/3 Wall St and J/Z Broad St", obstacles: "Perfect flatground, marble benches shaped like pixelated Cs", rating: 4, description: "The ledges are nice and slick. Fun to grind and if you can weave your manny skills should be a good time", bust_factor: "If you go during the week you will get kicked out, on the weekend it varies but usually you can get like 20mins to an hour.", noteworthy: "Watch NYC edits.", photo_main: "https://storage.googleapis.com/fsscs1/images/medium/cda2e75e77b959344bc9247076b513d2.jpg", photo2: "https://quartersnacks.com/wp-content/uploads/2010/05/c-benches-across-2.jpg", user_id: 1)

Spot.create( name: "Blue Park", address:"166 Manhattan Ave, Brooklyn, NY 11206", boro: "brooklyn", trains: "Montrose L, Broadway G, Lorimer J/M", obstacles: "Ever shifting array of DIY and always concrete manny pads with metal edges. Everything is titled.", rating: 5, description: "Has become a hot spot in the past couple years but still one of the chillest parks to skate at. New obstacles come and go but the basics are always there. If you go during the day pre-1/2pm you might run into school recess which can seriously put a bummer on the sesh.", bust_factor: "Not by any means, its a skatepark.", noteworthy: "erryday", photo_main: "https://quartersnacks.com/wp-content/uploads/2016/03/bluepark3.jpg", photo2: "https://lh3.googleusercontent.com/proxy/n7ieyrFJMKqWhaa1sAYDlBygcH5oBlmoIxXVlC6oHxUBF_2RibojwjeB36kkJzc9Pm6wOm_Fnn14XL5KgiBI5syt0UO35NJqFPjFayWmheZbUhX3R4n1FcOCsY8i", photo3: "https://i.ytimg.com/vi/_-jtNDXlqp0/hqdefault.jpg", user_id: 1)